# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: travelSearch.proto
# Protobuf Python Version: 4.25.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12travelSearch.proto\"\x82\x01\n\rTravelRequest\x12\x0e\n\x06origem\x18\x01 \x01(\t\x12\x0f\n\x07\x64\x65stino\x18\x02 \x01(\t\x12\x0e\n\x06\x63idade\x18\x03 \x01(\t\x12\x10\n\x08\x64\x61ta_ida\x18\x04 \x01(\t\x12\x12\n\ndata_volta\x18\x05 \x01(\t\x12\x1a\n\x12quantidade_adultos\x18\x06 \x01(\x05\"<\n\x0eTravelResponse\x12\x16\n\x06hoteis\x18\x01 \x03(\x0b\x32\x06.Hotel\x12\x12\n\x04voos\x18\x02 \x03(\x0b\x32\x04.Voo\"\xcf\x01\n\x05Hotel\x12\x12\n\nnome_hotel\x18\x01 \x01(\t\x12\x0e\n\x06\x63idade\x18\x02 \x01(\t\x12\x10\n\x08\x65ndereco\x18\x03 \x01(\t\x12\x13\n\x0bpreco_total\x18\x04 \x01(\x02\x12\x18\n\x10\x64\x65scricao_quarto\x18\x05 \x01(\t\x12\x14\n\x0c\x63heckin_date\x18\x06 \x01(\t\x12\x15\n\rcheckout_date\x18\x07 \x01(\t\x12\x1a\n\x12quantidade_adultos\x18\x08 \x01(\x05\x12\x18\n\x10\x63\x61tegoria_quarto\x18\t \x01(\t\"X\n\x03Voo\x12\x17\n\x0fhorario_partida\x18\x01 \x01(\t\x12\x17\n\x0fhorario_chegada\x18\x02 \x01(\t\x12\r\n\x05preco\x18\x03 \x01(\t\x12\x10\n\x08\x64\x65talhes\x18\x04 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'travelSearch_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_TRAVELREQUEST']._serialized_start=23
  _globals['_TRAVELREQUEST']._serialized_end=153
  _globals['_TRAVELRESPONSE']._serialized_start=155
  _globals['_TRAVELRESPONSE']._serialized_end=215
  _globals['_HOTEL']._serialized_start=218
  _globals['_HOTEL']._serialized_end=425
  _globals['_VOO']._serialized_start=427
  _globals['_VOO']._serialized_end=515
# @@protoc_insertion_point(module_scope)
